# -*- coding: utf-8 -*-
"""churn database Analaysis.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fc2e-SzkwBb4S7xtCBTyhg5SHYywbyd
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.preprocessing import OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, precision_score, recall_score, f1_score, roc_auc_score
import pickle

#data load

df = pd.read_csv(f'{path}/WA_Fn-UseC_-Telco-Customer-Churn.csv')
display(df.head())
# df.shape

df.info()

df.dtypes['TotalCharges']

# Convert 'TotalCharges' to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check the data type after conversion and look for any new NaN values
print(f"Data type of 'TotalCharges' after conversion: {df['TotalCharges'].dtype}")
print(f"Number of NaN values in 'TotalCharges': {df['TotalCharges'].isnull().sum()}")

df['TotalCharges'].fillna(0.0, inplace=True)

# Verify that there are no more NaN values in 'TotalCharges'
print(f"Number of NaN values in 'TotalCharges' after filling: {df['TotalCharges'].isnull().sum()}")

#customer i
df.columns

#drop the customer ID
df.drop(columns=['customerID'], inplace=True)

len(df[df['TotalCharges']==0.0])

num_feature=['tenure','MonthlyCharges','TotalCharges']
for col in df.columns:
  if col not in num_feature:
    print(col, df[col].unique())
    print("-"*50)

#null check
print(df.isnull().sum())

#class distrubutution for output col
df["Churn"].value_counts()

df.describe()

#Histogaram
def histogram(df,col_name):
  plt.figure(figsize=(5, 3))
  sns.histplot(df[col_name],kde=True)
  plt.xlabel(col_name)
  plt.ylabel('Frequency')
  plt.title(f'Histogram of {col_name}')
  _mean=df[col_name].mean()
  _median=df[col_name].median()
  plt.axvline(_mean,color='red',linestyle='dashed',linewidth=1,label='mean')
  plt.axvline(_median,color='green',linestyle='dotted',linewidth=1,label='median')
  plt.legend()
  plt.show()

  rel_diff = abs(_mean - _median) / _mean if _mean != 0 else 0

  if rel_diff < 0.05:
        assessment = "Symmetric enough"
  elif rel_diff < 0.20:
        assessment = "Moderately skewed - consider transform"
  else:
        assessment = "Highly skewed - must transform"

  print(f"\nColumn: {col_name}")
  print(f"Mean: {_mean:.4f}")
  print(f"Median: {_median:.4f}")
  print(f"Relative Difference: {rel_diff:.4f} ({rel_diff:.2%})")
  print(f"Assessment: {assessment}")

histogram(df,'tenure')

histogram(df,'MonthlyCharges')

histogram(df,'TotalCharges')

df['TotalCharges_log'] = np.log1p(df['TotalCharges'])

histogram(df,'TotalCharges_log')

def boxplot(df, col_name):

    plt.figure(figsize=(6, 4))

    # 1. Boxplot আঁকা
    sns.boxplot(x=df[col_name], color='skyblue', width=0.4)

    # 2. Title আর লেবেল
    plt.title(f'Boxplot of {col_name}')
    plt.xlabel(col_name)

    # 3. Mean (লাল) আর Median (সবুজ) লাইন
    _mean = df[col_name].mean()
    _median = df[col_name].median()

    plt.axvline(_mean, color='red', linestyle='--', linewidth=1.5, label=f'Mean: {_mean:.2f}')
    plt.axvline(_median, color='green', linestyle=':', linewidth=1.5, label=f'Median: {_median:.2f}')

    plt.legend()
    plt.tight_layout()
    plt.show()

    # 4. পরিসংখ্যান (Statistics) বের করা
    q1 = df[col_name].quantile(0.25)
    q3 = df[col_name].quantile(0.75)
    iqr = q3 - q1
    lower_fence = q1 - 1.5 * iqr
    upper_fence = q3 + 1.5 * iqr

    # Outlier সংখ্যা
    outliers = df[(df[col_name] < lower_fence) | (df[col_name] > upper_fence)][col_name]
    outlier_count = len(outliers)
    outlier_pct = (outlier_count / len(df)) * 100

    # Skewness (Mean vs Median)
    rel_diff = abs(_mean - _median) / _mean if _mean != 0 else 0

    # 5. কনসোলে কমেন্ট প্রিন্ট
    print(f"\n{'='*50}")
    print(f"📊 BOXPLT ANALYSIS: {col_name}")
    print(f"{'='*50}")
    print(f"Mean      : {_mean:.4f}")
    print(f"Median    : {_median:.4f}")
    print(f"Q1 (25%)  : {q1:.4f}")
    print(f"Q3 (75%)  : {q3:.4f}")
    print(f"IQR       : {iqr:.4f}")
    print(f"Lower Fence: {lower_fence:.4f}")
    print(f"Upper Fence: {upper_fence:.4f}")
    print(f"Outliers  : {outlier_count} ({outlier_pct:.2f}%)")
    print(f"Rel. Diff : {rel_diff:.4f} ({rel_diff:.2%})")
    print(f"{'='*50}")

    # 6. Interpretation / Comment
    comments = []

    # Skewness comment
    if _mean > _median:
        comments.append("📌 Right-skewed: Mean > Median (লেজ ডানদিকে লম্বা)")
    elif _mean < _median:
        comments.append("📌 Left-skewed: Mean < Median (লেজ বামদিকে লম্বা)")
    else:
        comments.append("✅ Symmetric: Mean ≈ Median")

    # Outlier comment
    if outlier_pct == 0:
        comments.append("✅ কোনো Outlier নেই।")
    elif outlier_pct < 1:
        comments.append(f"⚠️ অল্প কিছু Outlier আছে ({outlier_pct:.2f}%) — সমস্যা না।")
    elif outlier_pct < 5:
        comments.append(f"⚠️ Moderate Outliers ({outlier_pct:.2f}%) — Transform বা Capping ভাবতে পারেন।")
    else:
        comments.append(f"🔴 Heavy Outliers ({outlier_pct:.2f}%) — Robust Scaler / Log Transform মাস্ট!")

    # IQR vs Range comment
    data_range = df[col_name].max() - df[col_name].min()
    if iqr / data_range < 0.3:
        comments.append("🔴 Data অনেক ছড়ানো (Spread out) — Variance বেশি।")
    else:
        comments.append("✅ Data ভালোভাবে কনসেনট্রেটেড (Compact)।")

    # Print all comments
    print("\n💬 COMMENTS:")
    for c in comments:
        print(f"   {c}")
    print(f"{'='*50}\n")

boxplot(df, 'tenure')

boxplot(df, 'MonthlyCharges')

boxplot(df, 'TotalCharges')

boxplot(df, 'TotalCharges_log')

# 1. Heatmap (আপনার মতোই)
plt.figure(figsize=(8, 4))
cols = ["tenure", "MonthlyCharges", "TotalCharges"]
corr = df[cols].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", vmin=-1, vmax=1)
plt.title("Correlation Heatmap")
plt.show()

# 2. Auto Comments (value দেখেই)
print("\n" + "="*50)
print("📊 CORRELATION COMMENTS")
print("="*50)

for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        c1, c2 = cols[i], cols[j]
        v = corr.loc[c1, c2]

        if abs(v) >= 0.7:
            print(f"\n🔴 {c1} ↔ {c2}: {v:.2f}")
            print("   → HIGH correlation! Multicollinearity risk।")
            print("   → Linear Model-এ একটা বাদ দিন।")
        elif abs(v) >= 0.5:
            print(f"\n🟡 {c1} ↔ {c2}: {v:.2f}")
            print("   → Moderate correlation। চোখ রাখুন।")
        else:
            print(f"\n🟢 {c1} ↔ {c2}: {v:.2f}")
            print("   → Low correlation। ঠিক আছে, দুটোই রাখুন।")

print("\n" + "="*50)
print("💡 SUMMARY:")
if corr.abs().values[~np.eye(len(cols), dtype=bool)].max() >= 0.7:
    print("   • Tree model (RF/XGB): তিনটাই রাখতে পারেন ✅")
    print("   • Linear/Logistic: TotalCharges বাদ দিন ⚠️")
else:
    print("   • সব ফিচার ব্যবহার করতে পারেন ✅")
print("="*50)

import matplotlib.pyplot as plt
import seaborn as sns

# Target column name (Churn analysis এর জন্য, না চাইলে None রাখুন)
target_col = None # বা 'Churn_numeric' / None

object_cols = df.select_dtypes(include="object").columns.to_list()
object_cols = ["SeniorCitizen"] + object_cols

for col in object_cols:
    # ===== 1. Plot =====
    plt.figure(figsize=(6, 3.5))

    order = df[col].value_counts().index
    if len(order) > 10:
        order = order[:10]

    ax = sns.countplot(data=df, x=col, order=order, palette='Set2', edgecolor='black')
    plt.title(f'Count Plot of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')

    # বারের উপর count লেখা
    for p in ax.patches:
        h = p.get_height()
        if h > 0:
            ax.text(p.get_x() + p.get_width()/2., h, f'{int(h)}',
                   ha='center', va='bottom', fontsize=8)

    if max(len(str(x)) for x in order) > 5:
        plt.xticks(rotation=30, ha='right')

    plt.tight_layout()
    plt.show()

    # ===== 2. Stats & Comments =====
    counts = df[col].value_counts()
    pct = df[col].value_counts(normalize=True) * 100
    n_unique = df[col].nunique()

    print(f"\n{'='*50}")
    print(f"📊 {col} | Categories: {n_unique} | Missing: {df[col].isnull().sum()}")
    print(f"{'-'*50}")

    for cat in counts.index:
        print(f"   {str(cat):18s}: {counts[cat]:5d} ({pct[cat]:5.1f}%)")

    # Balance comment
    top_pct = pct.iloc[0]
    print(f"{'-'*50}")
    if top_pct > 90:
        print(f"🔴 IMBALANCED: '{counts.index[0]}' = {top_pct:.1f}% → Drop করুন!")
    elif top_pct > 70:
        print(f"⚠️  SKEWED: Top class {top_pct:.1f}% → Minor classes underrepresented")
    elif top_pct > 55:
        print(f"🟡 MODERATE: Top class {top_pct:.1f}% → Acceptable")
    else:
        print(f"✅ BALANCED: Fairly even distribution")

    # Cardinality
    if n_unique > 20:
        print(f"⚠️  HIGH CARDINALITY ({n_unique}) → Target encoding ভাবুন")
    elif n_unique == 2:
        print(f"✅ BINARY → Direct 0/1 encode করা যাবে")

    # Target relation (if provided)
    if target_col and target_col in df.columns:
        print(f"🎯 Churn Rate by {col}:")
        churn_rate = df.groupby(col)[target_col].apply(lambda x: (x=='Yes').mean()*100 if x.dtype=='object' else x.mean()*100)
        for cat in counts.index[:6]:
            if cat in churn_rate.index:
                print(f"   {str(cat):15s}: {churn_rate[cat]:5.1f}%")

    print(f"{'='*50}\n")

"""###Data Preposseing"""

# # Label encoding of target column
df["Churn"] = df["Churn"].replace({"Yes": 1, "No": 0})

X=df.drop(columns=['Churn'])
y=df['Churn']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

cat_col=X.select_dtypes(include=['object']).columns.tolist()
num_col=X.select_dtypes(include=['int64','float64']).columns.tolist()

preprocess=ColumnTransformer([
    ('cat',OneHotEncoder(drop='first',handle_unknown='ignore'),cat_col),
    ('num','passthrough',num_col)

])

#Pipeline
pipeline=ImbPipeline([
    ('preprocessor',preprocess),
    ('smote',SMOTE(random_state=42)),
    ('rfc',RandomForestClassifier(random_state=42))
])

# --------------------------------------------------
# 2. Define hyperparameter search space
# --------------------------------------------------
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
param_dist = {
    'rfc__n_estimators': randint(100, 500),        # number of trees
    'rfc__max_depth': [10, 20, 30, None],          # tree depth
    'rfc__min_samples_split': randint(2, 20),      # min samples to split a node
    'rfc__min_samples_leaf': randint(1, 10),       # min samples in a leaf
    'rfc__max_features': ['sqrt', 'log2', None],   # features per split
    'rfc__class_weight': ['balanced', 'balanced_subsample', None]  # handle imbalance
}

# --------------------------------------------------
# 3. Run RandomizedSearchCV
# --------------------------------------------------
random_search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_dist,
    n_iter=10,              # number of random combinations to try
    cv=5,                   # 5-fold cross-validation
    scoring='roc_auc',      # optimize for ROC-AUC (good for imbalanced)
    n_jobs=-1,              # use all CPU cores
    random_state=42,
    verbose=1               # show progress
)
print("Starting hyperparameter search...")
random_search.fit(X_train, y_train)

# --------------------------------------------------
# 4. Results
# --------------------------------------------------
print("\n" + "="*50)
print("BEST HYPERPARAMETERS FOUND:")
print("="*50)
for param, value in random_search.best_params_.items():
    print(f"{param}: {value}")

print(f"\nBest cross-validation ROC-AUC: {random_search.best_score_:.4f}")

#--------------------------------------------------
# 5. Evaluate best model on test set
# --------------------------------------------------
best_pipeline = random_search.best_estimator_
y_pred = best_pipeline.predict(X_test)
y_proba = best_pipeline.predict_proba(X_test)[:, 1]

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report

print("\n" + "="*50)
print("FINAL MODEL PERFORMANCE (After Tuning)")
print("="*50)
print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score:  {f1_score(y_test, y_pred):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test, y_proba):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

with open("churn_pipeline.pkl", "wb") as f:
    pickle.dump(pipeline, f)