# -*- coding: utf-8 -*-
"""churn Model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_yf5Vge4kUM7-tRM0KPXScVGPYJ7xjO
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("blastchar/telco-customer-churn")

print("Path to dataset files:", path)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, precision_score, recall_score, f1_score, roc_auc_score
import pickle

df = pd.read_csv(f'{path}/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Convert 'TotalCharges' to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

#  Verify that there are no more NaN values in 'TotalCharges'

df['TotalCharges'] = df['TotalCharges'].fillna(0.0)

#drop the customer ID
df.drop(columns=['customerID'], inplace=True)

df["Churn"] = df["Churn"].replace({"Yes": 1, "No": 0}).astype(int)

X=df.drop(columns=['Churn'])
y=df['Churn']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

cat_col=X.select_dtypes(include=['object']).columns.tolist()
num_col=X.select_dtypes(include=['int64','float64']).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_col),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_col),
    ]
)

rfc = RandomForestClassifier(
    n_estimators=439,
    max_depth=10,
    min_samples_split=3,
    min_samples_leaf=5,
    max_features="log2",
    class_weight="balanced_subsample",
    random_state=42,
    n_jobs=-1,
)

#Pipeline
pipeline = ImbPipeline([
    ("preprocessor", preprocessor),
    ("smote", SMOTE(random_state=42, k_neighbors=5)),
    ("rfc", rfc),  # your tuned model
])

pipeline.fit(X_train,y_train)

y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]
# y_pred

# Create a single customer's data for prediction
new_customer_data = {
    'gender': ['Male'],
    'SeniorCitizen': [0],
    'Partner': ['Yes'],
    'Dependents': ['No'],
    'tenure': [30],
    'PhoneService': ['Yes'],
    'MultipleLines': ['Yes'],
    'InternetService': ['Fiber optic'],
    'OnlineSecurity': ['No'],
    'OnlineBackup': ['Yes'],
    'DeviceProtection': ['No'],
    'TechSupport': ['No'],
    'StreamingTV': ['Yes'],
    'StreamingMovies': ['Yes'],
    'Contract': ['Month-to-month'],
    'PaperlessBilling': ['Yes'],
    'PaymentMethod': ['Electronic check'],
    'MonthlyCharges': [85.5],
    'TotalCharges': [2500.0]
}

new_df = pd.DataFrame(new_customer_data)
print("New customer data created:")
display(new_df)

# Predict using the properly trained pipeline
new_predictions = pipeline.predict(new_df)
new_probabilities = pipeline.predict_proba(new_df)[:, 1]

print(f"Prediction (1=Churn, 0=Stay): {new_predictions[0]}")
print(f"Churn Probability: {new_probabilities[0]:.2%}")

"""
**Model** Prediction: 1 (Churn)

**Churn** Probability: 78.32%

১. সিদ্ধান্ত (Prediction): কাস্টমারটি কোম্পানি ছেড়ে চলে যাবেন (Churn = 1)

২. সম্ভাবনা (Probability): টেস্ট কাস্টমারের ক্ষেত্রে মডেলটি ৭৮.৩২% নিশ্চিত যে তিনি চলে যাবেন"""

import pickle
from google.colab import files

# ১. পাইপলাইনটিকে 'churn_model.pkl' নামে সেভ করা
with open('churn_model.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

print("মডেলটি সফলভাবে সেভ হয়েছে!")

# ২. ফাইলটি সরাসরি আপনার কম্পিউটারে ডাউনলোড করা
files.download('churn_model.pkl')
